### ISSUE TITLE
Progress halted?

### ISSUE THREAD

**Issue by Martinspire** [gruntjs/grunt-next#3]
I was hearing some good things for this next version of Grunt. Is it halted or has it gone to a different channel of Grunt itself?

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt-legacy-file
https://github.com/gruntjs/grunt-legacy-config
https://github.com/gruntjs/grunt-legacy-template

**Comment by Martinspire** [comment]
Hmm, interesting. But why are they named legacy? If they are supposed to replace them i would imagine some naming like next or prototype?
